source("load_data.R")
png(file = "plot4.png", width = 480, height = 480, bg = "transparent")
par(mfrow = c(2, 2))
plot(sel_data$datetime, sel_data$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(sel_data$datetime, sel_data$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(sel_data$datetime, sel_data$Sub_metering_1, type = "l", ylim = range(sel_data$Sub_metering_1), xlab = "", ylab= "Energy sub metering")
par(new = TRUE)
plot(sel_data$datetime, sel_data$Sub_metering_2, type = "l", ylim = range(sel_data$Sub_metering_1), col = "red", xaxt = "n", yaxt = "n", xlab = "", ylab= "")
par(new = TRUE)
plot(sel_data$datetime, sel_data$Sub_metering_3, type = "l", ylim = range(sel_data$Sub_metering_1), col = "blue", xaxt = "n", yaxt = "n", xlab = "", ylab= "")
legend("topright",legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n", lty = c(1,1),col=c("black", "red", "blue"))
plot(sel_data$datetime, sel_data$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()