source("load_data.R")
png(file = "plot3.png", width = 480, height = 480, bg = "transparent")
plot(sel_data$datetime, sel_data$Sub_metering_1, type = "l", ylim = range(sel_data$Sub_metering_1), xlab = "", ylab= "Energy sub metering")
par(new = TRUE)
plot(sel_data$datetime, sel_data$Sub_metering_2, type = "l", ylim = range(sel_data$Sub_metering_1), col = "red", xaxt = "n", yaxt = "n", xlab = "", ylab= "")
par(new = TRUE)
plot(sel_data$datetime, sel_data$Sub_metering_3, type = "l", ylim = range(sel_data$Sub_metering_1), col = "blue", xaxt = "n", yaxt = "n", xlab = "", ylab= "")
legend("topright",legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1),col=c("black", "red", "blue"))
dev.off()